package GarageCorba;


/**
* GarageCorba/IGarageRemoteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Garage.idl
* vendredi 14 décembre 2018 23 h 11 WET
*/

abstract public class IGarageRemoteHelper
{
  private static String  _id = "IDL:GarageCorba/IGarageRemote:1.0";

  public static void insert (org.omg.CORBA.Any a, GarageCorba.IGarageRemote that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GarageCorba.IGarageRemote extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GarageCorba.IGarageRemoteHelper.id (), "IGarageRemote");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GarageCorba.IGarageRemote read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IGarageRemoteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GarageCorba.IGarageRemote value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GarageCorba.IGarageRemote narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GarageCorba.IGarageRemote)
      return (GarageCorba.IGarageRemote)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GarageCorba._IGarageRemoteStub stub = new GarageCorba._IGarageRemoteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GarageCorba.IGarageRemote unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GarageCorba.IGarageRemote)
      return (GarageCorba.IGarageRemote)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GarageCorba._IGarageRemoteStub stub = new GarageCorba._IGarageRemoteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
