package GarageCorba;


/**
* GarageCorba/Voiture.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Garage.idl
* vendredi 14 décembre 2018 23 h 11 WET
*/

public final class Voiture implements org.omg.CORBA.portable.IDLEntity
{
  public String src_garage = null;
  public String name = null;

  public Voiture ()
  {
  } // ctor

  public Voiture (String _src_garage, String _name)
  {
    src_garage = _src_garage;
    name = _name;
  } // ctor

} // class Voiture
