package GarageCorba;


/**
* GarageCorba/IGarageRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Garage.idl
* vendredi 14 décembre 2018 23 h 15 WET
*/

public interface IGarageRemote extends IGarageRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IGarageRemote
