package GarageCorba;

/**
* GarageCorba/IGarageRemoteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Garage.idl
* vendredi 14 décembre 2018 23 h 15 WET
*/

public final class IGarageRemoteHolder implements org.omg.CORBA.portable.Streamable
{
  public GarageCorba.IGarageRemote value = null;

  public IGarageRemoteHolder ()
  {
  }

  public IGarageRemoteHolder (GarageCorba.IGarageRemote initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GarageCorba.IGarageRemoteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GarageCorba.IGarageRemoteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GarageCorba.IGarageRemoteHelper.type ();
  }

}
