package GarageCorba;


/**
* GarageCorba/IGarageRemotePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Garage.idl
* vendredi 14 décembre 2018 23 h 04 WET
*/

public abstract class IGarageRemotePOA extends org.omg.PortableServer.Servant
 implements GarageCorba.IGarageRemoteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("Restituer", new java.lang.Integer (0));
    _methods.put ("Louer", new java.lang.Integer (1));
    _methods.put ("afficheVoitures", new java.lang.Integer (2));
    _methods.put ("maVoiture", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // GarageCorba/IGarageRemote/Restituer
       {
         GarageCorba.Voiture v = GarageCorba.VoitureHelper.read (in);
         this.Restituer (v);
         out = $rh.createReply();
         break;
       }

       case 1:  // GarageCorba/IGarageRemote/Louer
       {
         GarageCorba.Voiture v = GarageCorba.VoitureHelper.read (in);
         this.Louer (v);
         out = $rh.createReply();
         break;
       }

       case 2:  // GarageCorba/IGarageRemote/afficheVoitures
       {
         GarageCorba.Voiture $result[] = null;
         $result = this.afficheVoitures ();
         out = $rh.createReply();
         GarageCorba.tabVoituresHelper.write (out, $result);
         break;
       }

       case 3:  // GarageCorba/IGarageRemote/maVoiture
       {
         String name = in.read_string ();
         GarageCorba.Voiture $result = null;
         $result = this.maVoiture (name);
         out = $rh.createReply();
         GarageCorba.VoitureHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GarageCorba/IGarageRemote:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IGarageRemote _this() 
  {
    return IGarageRemoteHelper.narrow(
    super._this_object());
  }

  public IGarageRemote _this(org.omg.CORBA.ORB orb) 
  {
    return IGarageRemoteHelper.narrow(
    super._this_object(orb));
  }


} // class IGarageRemotePOA
